- name: Archiving OpenBoxes database (please allow 5-10 minutes)
  hosts: dbservers:localhost
  vars:
    archive_file: openboxes.tgz
    db_username: openboxes
    use_sudo: false

  tasks:

    - name: Dumping database (this can be slow)
      register: archive_db
      ansible.builtin.script:
        cmd: >
          ../scripts/archive_db.bash {{ '-s' if use_sudo else '' }}
          -d {{ inventory.db_name }} -o {{ archive_file }} -u {{ db_username }}
      environment:
        DB_USER_PASSWORD: "{{ vault.db_users[db_username].password }}"

    - name: Collecting script output
      when: archive_db.stdout_lines is defined
      ansible.builtin.debug:
        msg:
          - "{{ archive_db.stdout_lines | regex_replace(vault.db_users[db_username].password, '********') }}"
          - "{{ archive_db.stderr_lines | regex_replace(vault.db_users[db_username].password, '********') }}"

    - name: Fetching archive file from remote host (this can be slow, too)
      ansible.builtin.fetch:
        dest: ../build/archive_db
        src: "{{ archive_file }}"

    - name: Deleting archive file from remote host after copying
      ansible.builtin.file:
        path: "{{ archive_file }}"
        state: absent
