# this file requires ZeroTier access (network ID c7c8172af1a86915)

prd:
  hosts:
    obnav:
      ansible_host: 10.160.28.10
  vars:
    production: true

stg:
  hosts:
    obnavstg:
      ansible_host: 10.160.28.11

dev:
  hosts:
    obdev:
      ansible_host: 10.160.28.12

dbservers:
  children:
    dev:
    prd:
    stg:

webservers:
  children:
    dev:
    prd:
    stg:

azure:
  children:
    dev:
    prd:
    stg:
  vars:
    ansible_port: 22
    ansible_ssh_private_key_file: ~/.ssh/ansible_ed25519
    ansible_user: root
