all:
  vars:
    ansible_port: 22
    ansible_ssh_private_key_file: ~/.ssh/ansible_ed25519
    ansible_user: root
    inventory: &common_inventory
      app_context: /openboxes
      bamboo:
        project_ids:
          - 3735553
        remote_agent_home: /home/bamboo/remote-agent
        server_url: https://bamboo-ci.pih-emr.org
      db_name: openboxes
      mail:
        admins:
          - justin@openboxes.com
          - mpearson@pih.org
        bcc:
          - justin@openboxes.com
          - mpearson@pih.org
        host: smtp.sendgrid.net
        port: 587
        recipients:
          - openboxes@pih.org
        sender: openboxes@pih.org
        username: apikey
      mysql: &common_mysql
        innodb_use_native_aio: 1
        long_query_time: 1
        query_cache_size: 16777216  # 16 MBytes
        query_cache_type: 1
        slow_query_log: 1
      tomcat: &common_tomcat
        newsize: 256m

  children:
    big_webservers:
      vars:
        inventory: &big_webserver_inventory
          <<: *common_inventory
          grails:
            quartz_threads: 8
            send_mail: true
          mysql:
            <<: *common_mysql
            enabled: false
          tomcat:
            <<: *common_tomcat
            enabled: true
            gc_threads: 5
            gpars_poolsize: 8
            jdk: zulu7
            maxpermsize: 1024m
            name: tomcat7
            permsize: 512m
            xms: 6144m
            xmx: 6144m
      hosts:
        obprd:
          ansible_host: 74.50.49.135
          inventory:
            <<: *big_webserver_inventory
            db_url: jdbc:mysql://dbprd.pih-emr.org:3306/openboxes
        obstg:
          ansible_host: 74.50.49.133
          inventory:
            <<: *big_webserver_inventory
            db_url: jdbc:mysql://dbstg.pih-emr.org:3306/openboxes

    big_dbservers:
      vars:
        inventory: &big_dbserver_inventory
          <<: *common_inventory
          firewall:
            finance_hosts:
              ips:
                - 35.82.194.80
                - 35.83.121.11
                - 44.229.76.29
                - 44.231.117.185
                - 44.242.112.145
                - 52.89.22.131
                - 54.191.255.196
                - 54.213.236.166
              port: 3306
              users:
                - finance
            pih_cld_whdev:
              ips:
                - 40.70.215.46
              port: 3306
              users:
                - finance
            pih_cld_whprod:
              ips:
                - 52.177.217.36
              port: 3306
              users:
                - finance
            soldevelo:
              ips:
                - 194.181.116.130
              port: 3306
          mysql:
            <<: *common_mysql
            enabled: true
            innodb_buffer_pool_size: 17179869184  # 16 GBytes
          tomcat:
            enabled: false
      hosts:
        dbprd:
          ansible_host: 74.50.49.138
          inventory:
            <<: *big_dbserver_inventory
            remote_webserver: 74.50.49.135
        dbstg:
          ansible_host: 74.50.49.124
          inventory:
            <<: *big_dbserver_inventory
            remote_webserver: 74.50.49.133

    little_instances:
      vars:
        inventory: &little_instance_inventory
          <<: *common_inventory
          db_url: jdbc:mysql://localhost:3306/openboxes
          grails:
            quartz_threads: 4
            send_mail: false
          mysql:
            <<: *common_mysql
            enabled: true
            innodb_buffer_pool_size: 1073741824  # 1 GByte
          tomcat: &little_tomcat
            <<: *common_tomcat
            enabled: true
            gc_threads: 3
            gpars_poolsize: 4
            maxpermsize: 512m
            permsize: 256m
            xms: 3072m
            xmx: 3072m
      hosts:
        obdev1:
          ansible_host: 74.50.49.109
          inventory:
            <<: *little_instance_inventory
            openboxes:
              hotjar:
                enabled: true
                identifier: 3443850
                snippetVersion: 6
            tomcat:
              <<: *little_tomcat
              jdk: zulu7
              name: tomcat7
        obdev2:
          ansible_host: 74.50.49.117
          inventory:
            <<: *little_instance_inventory
            tomcat:
              <<: *little_tomcat
              jdk: zulu7
              name: tomcat7
        obdev3:
          ansible_host: 74.50.49.122
          inventory:
            <<: *little_instance_inventory
            tomcat:
              <<: *little_tomcat
              jdk: zulu7
              name: tomcat85
        obdev4:
          ansible_host: 74.50.49.134
          inventory:
            <<: *little_instance_inventory
            tomcat:
              <<: *little_tomcat
              jdk: zulu8
              name: tomcat85
    bamboo_remote_agents:
      hosts:
        obdev1:
        obdev2:
        obdev3:
        obdev4:
    dev:
      hosts:
        obdev1:
        obdev2:
        obdev3:
        obdev4:
    prd:
      hosts:
        obprd:
        dbprd:
    stg:
      hosts:
        obstg:
        dbstg:
