all:
  vars:
    ansible_port: 22
    ansible_ssh_private_key_file: ~/.ssh/ansible_ed25519
    ansible_user: root
    inventory: &common_inventory
      app_context: /openboxes
      backup_target: openboxes@host-90420072.bakop.com
      db_name: openboxes
      db_type: mariadb
      mail:
        admins:
          - justin@openboxes.com
          - mpearson@pih.org
        bcc:
          - justin@openboxes.com
          - mpearson@pih.org
        host: smtp.sendgrid.net
        port: 587
        recipients:
          - openboxes@pih.org
        sender: openboxes@pih.org
        username: apikey
      mysql: &common_mysql
        # settings in the `mysql` block will affect MariaDB and MySQL 8.0
        innodb_use_native_aio: 1
        long_query_time: 1
        query_cache_size: 67108864  # 64 MBytes
        slow_query_log: 1
      tomcat: &common_tomcat
        newsize: 256m

  children:
    big_webservers:
      vars:
        inventory: &big_webserver_inventory
          <<: *common_inventory
          google_analytics_web_property_id: 'UA-37396941-1'
          grails:
            quartz_threads: 8
            send_mail: true
          mysql:
            <<: *common_mysql
            enabled: false
          swap_size: 32GiB  # argument to fallocate -l
          tomcat: &big_tomcat
            <<: *common_tomcat
            enabled: true
            gc_threads: 5
            gpars_poolsize: 8
            jdk: zulu7
            maxpermsize: 1024m
            name: tomcat7
            permsize: 512m
            xms: 6144m
            xmx: 6144m
      hosts:
        obnav:
          ansible_host: 74.50.49.135
          inventory:
            <<: *big_webserver_inventory
            additional_domains:
              - obprd.pih-emr.org
              - openboxes.pih-emr.org
            db_url: jdbc:mysql://dbprd.pih-emr.org:3306/openboxes?allowPublicKeyRetrieval=true&dumpQueriesOnException=true&includeInnodbStatusInDeadlockExceptions=false&useSSL=false
            hotjar:
              enabled: true
              identifier: 3443850
              snippetVersion: 6
            tomcat:
              <<: *big_tomcat
              maxpermsize: 2048m
              xms: 12288m
              xmx: 12288m
        obnavstage:
          ansible_host: 74.50.49.133
          inventory:
            <<: *big_webserver_inventory
            additional_domains:
              - obstg.pih-emr.org
            db_url: jdbc:mysql://dbstg.pih-emr.org:3306/openboxes?allowPublicKeyRetrieval=true&dumpQueriesOnException=true&includeInnodbStatusInDeadlockExceptions=false&useSSL=false

    big_dbservers:
      vars:
        inventory: &big_dbserver_inventory
          <<: *common_inventory
          firewall:
            jmiranda:
              ips:
                - 65.29.169.164
              port: 3306
            knagel:
              ips:
                - 10.160.28.102
              port: 3306
              users:
                - knagel
            pih_cld_whdev:
              ips:
                - 40.70.215.46
              port: 3306
              require_mysql_ssl: false
              users:
                - finance
            pih_cld_whprod:
              ips:
                - 52.177.217.36
              port: 3306
              require_mysql_ssl: false
              users:
                - finance
            rapidi:
              ips:
                - 44.231.117.185
                - 52.89.22.131
              port: 3306
              require_mysql_ssl: true
              users:
                - finance
            soldevelo:
              ips:
                - 194.181.116.130
              port: 3306
          mysql:
            <<: *common_mysql
            enabled: true
            innodb_buffer_pool_size: 17179869184  # 16 GBytes
          tomcat:
            enabled: false
      hosts:
        dbprd:
          ansible_host: 74.50.49.138
          inventory:
            <<: *big_dbserver_inventory
            remote_webserver: 74.50.49.135
        dbstg:
          ansible_host: 74.50.49.124
          inventory:
            <<: *big_dbserver_inventory
            remote_webserver: 74.50.49.133

    little_instances:
      vars:
        inventory: &little_instance_inventory
          <<: *common_inventory
          db_url: jdbc:mysql://localhost:3306/openboxes?allowPublicKeyRetrieval=true&dumpQueriesOnException=true&includeInnodbStatusInDeadlockExceptions=false&useSSL=false
          grails:
            quartz_threads: 4
            send_mail: false
          mysql:
            <<: *common_mysql
            enabled: true
            innodb_buffer_pool_size: 1073741824  # 1 GByte
          tomcat: &little_tomcat
            <<: *common_tomcat
            enabled: true
            gc_threads: 3
            gpars_poolsize: 4
            maxpermsize: 512m
            permsize: 256m
            xms: 3072m
            xmx: 3072m
      hosts:
        obdev1:
          ansible_host: 74.50.49.109
          inventory:
            <<: *little_instance_inventory
            openboxes:
              hotjar:
                enabled: true
                identifier: 3443850
                snippetVersion: 6
            tomcat:
              <<: *little_tomcat
              jdk: zulu7
              name: tomcat7
        obdev2:
          ansible_host: 74.50.49.117
          inventory:
            <<: *little_instance_inventory
            tomcat:
              <<: *little_tomcat
              jdk: zulu7
              name: tomcat7
        obdev3:
          ansible_host: 74.50.49.122
          inventory:
            <<: *little_instance_inventory
            tomcat:
              <<: *little_tomcat
              jdk: zulu8
              name: tomcat85
        obdev4:
          ansible_host: 74.50.49.134
          inventory:
            <<: *little_instance_inventory
            tomcat:
              <<: *little_tomcat
              jdk: zulu7
              name: tomcat7
        obdev5:
          ansible_host: 74.50.48.61
          inventory:
            <<: *little_instance_inventory
            db_type: mysql
            tomcat:
              <<: *little_tomcat
              jdk: zulu7
              name: tomcat7
    bamboo_remote_agents:
      vars:
        inventory:
          <<: *common_inventory
          bamboo:
            project_ids:
              - 3735553
            remote_agent_home: /home/bamboo/remote-agent
            server_url: https://bamboo-ci.pih-emr.org
          swap_size: 10GiB  # argument to fallocate -l
      hosts:
        obagent1:
          ansible_host: 74.50.48.53
        obagent2:
          ansible_host: 74.50.48.161
    personal:
      vars:
        ansible_connection: local
        ansible_python_interpreter: "{{ansible_playbook_python}}"
        inventory:
          <<: *common_inventory
          db_url: jdbc:mysql://localhost:3306/openboxes?allowPublicKeyRetrieval=true&dumpQueriesOnException=true&includeInnodbStatusInDeadlockExceptions=false&useSSL=false
          mysql:
            <<: *common_mysql
            enabled: true
            innodb_buffer_pool_size: 268435456  # 256 MBytes
          tomcat:
            <<: *common_tomcat
            enabled: true
            maxpermsize: 512m
            permsize: 256m
            xms: 2048m
            xmx: 2048m
      hosts:
        localhost:
    dev:
      hosts:
        obdev1:
        obdev2:
        obdev3:
        obdev4:
        obdev5:
    prd:
      hosts:
        obnav:
        dbprd:
    stg:
      hosts:
        obnavstage:
        dbstg:
    dbservers:
      children:
        big_dbservers:
        dev:
    webservers:
      children:
        big_webservers:
        dev:
