# Requires `ansible-galaxy collection install community.general`

- name: Applying security measures
  hosts: all
  tasks:

    - name: Installing ClamAV
      register: apt_install
      ansible.builtin.apt:
        cache_valid_time: 3600
        install_recommends: true
        state: latest
        update_cache: true
        pkg:
          - clamav
          - clamav-daemon
          - libclamunrar9

    - name: Enabling ssh, http and https access
      community.general.ufw:
        port: "{{ item }}"
        proto: tcp
        rule: allow
      loop:
        - 22
        - 80
        - 443

    - name: Enabling remote DB access from finance hosts
      when: inventory.get('finance_hosts')
      community.general.ufw:
        port: 3306
        proto: tcp
        rule: allow
        src: "{{ item }}"
      loop: "{{ inventory.finance_hosts }}"

    - name: Enabling remote DB access from paired webserver
      when: inventory.get('remote_webserver')
      community.general.ufw:
        port: 3306
        proto: tcp
        rule: allow
        src: "{{ inventory.remote_webserver }}"

    - name: Limiting brute-force ssh login attempts
      community.general.ufw:
        port: 22
        proto: tcp
        rule: limit

    - name: Enabling firewall, with logging
      community.general.ufw:
        logging: 'on'
        policy: reject
        state: enabled
