# Requires `ansible-galaxy collection install ansible.posix`

- name: Enabling deployment and remote restart with Bamboo
  hosts: all
  tasks:

    - name: Adding bamboo user
      ansible.builtin.user:
        create_home: true
        group: "{{ item.group }}"
        groups: "{{ item.groups }}"
        name: "{{ item.name }}"
        password: '!'
        system: "{{ item.system | bool }}"
        uid: "{{ item.uid }}"
      loop:
        - group: staff
          groups: tomcat
          name: bamboo
          system: false
          uid: 1509

    - name: Adding authorized public keys for bamboo user
      when: 'lookup("ansible.builtin.fileglob", item.key_file) != []'
      ansible.posix.authorized_key:
        key: "{{ lookup('ansible.builtin.file', item.key_file) }}"
        state: present
        user: "{{ item.user }}"
      loop:
        - key_file: ../public_keys/bamboo_ed25519.pub
          user: bamboo

    - name: Enabling limited sudo access for bamboo user
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
        validate: visudo -cf %s
      loop:
        - line: 'bamboo ALL=(ALL) NOPASSWD:/sbin/service,/usr/sbin/service'
          regexp: '^bamboo'

    - name: Adding restart-tomcat script for Bamboo
      when: inventory.get('tomcat', {}).get('enabled')
      ansible.builtin.template:
        dest: /opt/restart-tomcat.sh
        group: staff
        mode: '0550'
        owner: bamboo
        src: ../templates/restart-tomcat.sh.j2

    #
    # The following task ignores Tomcat best practices, but Bamboo needs it to work.
    #
    # > It is recommended to never grant the manager-script or
    # > manager-jmx roles to users that have the manager-gui role.
    #
    # https://tomcat.apache.org/tomcat-8.5-doc/manager-howto.html#Configuring_Manager_Application_Access
    #
    - name: Injecting bamboo user in Tomcat manager
      ansible.builtin.lineinfile:
        insertbefore: '^</tomcat-users>'
        # https://confluence.atlassian.com/bamboo/using-tomcat-with-bamboo-for-continuous-deployment-305759758.html
        line: '  <user username="bamboo" password="{{ vault.tomcat_users.bamboo.password }}" roles="manager-gui,manager-script" /> <!-- ANSIBLE MANAGED -->'
        path: "/var/lib/{{ item }}/conf/tomcat-users.xml"
        regexp: 'username="bamboo"'
      loop:
        - tomcat7
        - tomcat85

    - name: Restarting Tomcat service on web-serving hosts
      when: inventory.get('tomcat', {}).get('enabled')
      block:

        - name: Declaring deployment targets
          ansible.builtin.set_fact:
            deployment_targets:
              - "/var/lib/tomcat7/webapps{{ inventory.app_context }}"
              - "/var/lib/tomcat85/webapps{{ inventory.app_context }}"

        - name: Creating deployment directories if not present
          ansible.builtin.file:
            group: tomcat
            mode: '0750'
            owner: tomcat
            path: "{{ item }}"
            state: directory
          loop: "{{ deployment_targets }}"

        - name: Restarting Tomcat service on web-serving hosts
          ansible.builtin.systemd:
            daemon_reload: true
            enabled: true
            name: tomcat
            state: restarted

        - name: Checking for existing deployments
          register: find_results
          ansible.builtin.find:
            depth: 1
            paths: "{{ deployment_targets }}"

        - name: Enabling empty deploy via Tomcat manager
          when: find_results.matched == 0
          block:

            - name: Pause until Tomcat manager is up
              register: tomcat_manager
              ansible.builtin.uri:
                password: "{{ vault.tomcat_users.bamboo.password }}"
                url: http://localhost:8080/manager/text
                user: bamboo
              until: tomcat_manager.status == 200

            - name: Starting a dummy deploy so Bamboo has something to replace
              ansible.builtin.uri:
                password: "{{ vault.tomcat_users.bamboo.password }}"
                url: http://localhost:8080/manager/text/start?path={{ inventory.app_context }}
                user: bamboo
