# Requires `ansible-galaxy collection install community.general`

- name: Applying security measures
  hosts: all
  tasks:

    - name: Installing ClamAV
      register: apt_install
      ansible.builtin.apt:
        cache_valid_time: 3600
        install_recommends: true
        state: latest
        update_cache: true
        pkg:
          - clamav
          - clamav-daemon
          - libclamunrar9

    - name: Enabling ssh access while limiting brute-force login attempts
      community.general.ufw:
        comment: allow ssh but defend against brute-force login attempts
        port: 22
        proto: tcp
        rule: limit

    - name: Enabling http(s) access on web-serving hosts
      when: inventory.get('tomcat', {}).get('enabled')
      community.general.ufw:
        comment: allow http(s) access from anywhere
        port: "{{ item }}"
        proto: tcp
        rule: allow
      loop:
        - 80
        - 443

    - name: Applying firewall rules from inventory
      when: inventory.get('firewall')
      community.general.ufw:
        comment: "allow access from {{ item[0].key }}"
        port: "{{ item[0].value.port }}"
        proto: tcp
        rule: allow
        src: "{{ item[1] }}"
      loop: >-
        {{ inventory.firewall
         | dict2items
         | subelements('value.ips')
         | rejectattr('1', 'equalto', 'localhost') }}

    - name: Activating firewall, with logging
      community.general.ufw:
        logging: 'on'
        policy: reject
        state: enabled
