- name: Deploying OpenBoxes war file (please allow 5-10 minutes)
  hosts: webservers
  tasks:

    - name: Ensuring explicit choice of host(s)
      run_once: true
      when: ansible_limit is not defined
      ansible.builtin.fail:
        msg: "you must use -l or --limit! If you really want to use all hosts, use -l 'all'"

    - name: Ensuring target host is a web server
      when: webserver is not defined
      ansible.builtin.fail:
        msg: 'this host has no webserver specified in inventory'

    - name: Checking service status
      ansible.builtin.service_facts:

    - name: Deploying war file
      block:

        - name: Stopping Tomcat service
          ansible.builtin.systemd:
            daemon_reload: true
            name: tomcat
            state: stopped

        - name: Stopping mysql service, if enabled
          when: ansible_facts.services['mysql.service'].state in ('active', 'running')
          ansible.builtin.systemd:
            daemon_reload: true
            name: mysql
            state: stopped

        - name: Removing previous deployment
          ansible.builtin.file:
            path: "/var/lib/{{ webserver }}/webapps{{ app_context }}"
            state: absent

        - name: Uploading war file to remote host
          ansible.builtin.copy:
            dest: "/var/lib/{{ webserver }}/webapps{{ app_context }}.war"
            group: tomcat
            mode: '0440'
            owner: tomcat
            src: "{{ war_path }}/{{ war_file }}"

      always:

        - name: Restarting mysql service, if enabled
          when: ansible_facts.services['mysql.service'].state in ('active', 'running')
          ansible.builtin.systemd:
            daemon_reload: true
            name: mysql
            state: restarted

        - name: Restarting Tomcat service
          ansible.builtin.systemd:
            daemon_reload: true
            name: tomcat
            state: restarted

    - name: "Waiting for 200 from https://$remote_host{{ app_context }}"
      delay: 15
      register: https_response
      retries: 60
      until: https_response.status == 200
      ansible.builtin.uri:
        url: "https://{{ ansible_fqdn }}{{ app_context }}"

  vars:
    war_file: 'openboxes-0.8.21-SNAPSHOT.war'
    war_path: '../../openboxes/target'
